/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Local-auth requires user session; demo remains explicit fixed fixtures. Management views require the separate password/TOTP admin listener. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Local-auth requires user session; demo remains explicit fixed fixtures. Management views require the separate password/TOTP admin listener. */
        get: operations["devices"];
        put?: never;
        /**
         * Local user device intent: /devices
         * @description Authenticated owner only. Mutations require Origin/CSRF and JSON. Request creates two pending profile slots without keys or peer provisioning. Cancellation only before any configured profile/subscription; it is not a network revoke. request_id is owner-scoped idempotency, same payload required; expected_revision protects updates.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceRequest"];
                };
            };
            responses: {
                /** @description Current result (including idempotent replay) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Login required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Origin/CSRF rejected */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found or not owned */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Limit, revision, idempotency payload or state conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Local-auth requires user session; demo remains explicit fixed fixtures. Management views require the separate password/TOTP admin listener. */
        get: operations["devices_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Local-auth requires user session; demo remains explicit fixed fixtures. Management views require the separate password/TOTP admin listener. */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Local-auth requires user session; demo remains explicit fixed fixtures. Management views require the separate password/TOTP admin listener. */
        get: operations["instructions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Available ONLY on the admin listener :8081. Local-auth requires user session; demo remains explicit fixed fixtures. Management views require the separate password/TOTP admin listener. */
        get: operations["admin_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Local-auth requires user session; demo remains explicit fixed fixtures. Management views require the separate password/TOTP admin listener. */
        get: operations["downloadDemoProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Local HTTPS only. Exact Host/Origin. POST requires JSON <=64 KiB and CSRF header. All responses no-store; no token in URL. No public registration. */
        get: operations["authBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Local HTTPS only. Exact Host/Origin. POST requires JSON <=64 KiB and CSRF header. All responses no-store; no token in URL. No public registration. */
        post: operations["passwordLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Local HTTPS only. Exact Host/Origin. POST requires JSON <=64 KiB and CSRF header. All responses no-store; no token in URL. No public registration. */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Local HTTPS only. Exact Host/Origin. POST requires JSON <=64 KiB and CSRF header. All responses no-store; no token in URL. No public registration. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/touch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Local HTTPS only. Exact Host/Origin. POST requires JSON <=64 KiB and CSRF header. All responses no-store; no token in URL. No public registration. */
        post: operations["touchSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recovery/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Local HTTPS user-only recovery. Issuance is trusted CLI only and immediately disables old password and revokes sessions. This endpoint consumes a single-use recovery token, saves a new password, revokes remaining tokens/sessions, clears cookies and does not auto-login. Preauth CSRF, exact Origin, JSON <=64 KiB. No changes to VPN profiles. */
        post: operations["consumeRecovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Closed local admin listener only: password
         * @description HTTPS numeric loopback. Separate admin preauth cookie and X-CSRF-Token, exact Origin. Password creates a 3 minute challenge bound to preauth cookie; only TOTP creates an admin session (12h absolute / 30m idle). Never registered on public portal.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordLogin"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminChallenge"];
                    };
                };
                /** @description Authentication denied */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Origin or CSRF rejected */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Attempts limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Closed local admin listener only: totp
         * @description HTTPS numeric loopback. Separate admin preauth cookie and X-CSRF-Token, exact Origin. Password creates a 3 minute challenge bound to preauth cookie; only TOTP creates an admin session (12h absolute / 30m idle). Never registered on public portal.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminTOTP"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminAuthResult"];
                    };
                };
                /** @description Authentication denied */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Origin or CSRF rejected */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Attempts limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Local user device intent: /devices/quota
         * @description Authenticated owner only. Mutations require Origin/CSRF and JSON. Request creates two pending profile slots without keys or peer provisioning. Cancellation only before any configured profile/subscription; it is not a network revoke. request_id is owner-scoped idempotency, same payload required; expected_revision protects updates.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current result (including idempotent replay) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceQuota"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Login required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Origin/CSRF rejected */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found or not owned */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Limit, revision, idempotency payload or state conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Local user device intent: /devices/{id}/rename
         * @description Authenticated owner only. Mutations require Origin/CSRF and JSON. Request creates two pending profile slots without keys or peer provisioning. Cancellation only before any configured profile/subscription; it is not a network revoke. request_id is owner-scoped idempotency, same payload required; expected_revision protects updates.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceRename"];
                };
            };
            responses: {
                /** @description Current result (including idempotent replay) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Login required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Origin/CSRF rejected */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found or not owned */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Limit, revision, idempotency payload or state conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Local user device intent: /devices/{id}/cancel
         * @description Authenticated owner only. Mutations require Origin/CSRF and JSON. Request creates two pending profile slots without keys or peer provisioning. Cancellation only before any configured profile/subscription; it is not a network revoke. request_id is owner-scoped idempotency, same payload required; expected_revision protects updates.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceRevision"];
                };
            };
            responses: {
                /** @description Current result (including idempotent replay) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Login required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Origin/CSRF rejected */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found or not owned */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Limit, revision, idempotency payload or state conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Authenticated management listener only. Public and demo listeners do not expose this route. Read-only metadata with keyset pagination; no credentials, config, server keys or raw audit payloads. */
        get: operations["adminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Authenticated management listener only. Public and demo listeners do not expose this route. Read-only metadata with keyset pagination; no credentials, config, server keys or raw audit payloads. */
        get: operations["adminDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Authenticated management listener only. Public and demo listeners do not expose this route. Read-only metadata with keyset pagination; no credentials, config, server keys or raw audit payloads. */
        get: operations["adminAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructions/{id}/offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Local authenticated catalog only. Downloads non-secret self-contained HTML. No personalized data/configs or third-party requests; client draft verification is separate from portal verification. No query params. */
        get: operations["offlineGuide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Profile: {
            id: string;
            /** @enum {string} */
            protocol: "awg" | "reality";
            /** @enum {string} */
            state: "ready" | "pending" | "revoking" | "revoked" | "error";
            /**
             * @description Empty means unselected; txt is demo only; vless-reality-uri and awg-3.1-conf are imported client data that remain pending until installation verification.
             * @enum {string}
             */
            format: "txt" | "" | "vless-reality-uri" | "awg-3.1-conf";
        };
        Device: {
            id: string;
            name: string;
            os: string;
            state: string;
            profiles: components["schemas"]["Profile"][];
            revision: number;
        };
        Health: {
            component: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "unavailable" | "unknown";
            reason: string;
            /** Format: date-time */
            measured_at: string;
            /** Format: date-time */
            expires_at: string;
        };
        Instruction: {
            id: string;
            os: string;
            title: string;
            verified: boolean;
            steps: string[];
            /** @enum {string} */
            kind?: "portal" | "vpn";
            content_version?: number;
            /** Format: date */
            verified_at?: string;
            /** @enum {string} */
            verification_scope?: "none" | "portal" | "client";
            app_id?: string;
            app_version?: string;
            /** @enum {string} */
            protocol?: "awg" | "reality";
            format?: string;
            offline_available: boolean;
        };
        Me: {
            id: string;
            display_name: string;
            /** @enum {string} */
            role: "user" | "admin";
            /** @enum {string} */
            mode: "demo" | "local-auth" | "local-admin";
            /** @enum {string} */
            storage: "sqlite" | "memory-fixture";
            /** @description Only local-auth; held in JS memory, never localStorage. */
            csrf_token?: string;
        };
        Overview: {
            /** @enum {string} */
            mode: "demo" | "local-admin";
            total_devices: number;
            /** @constant */
            mutations_enabled: false;
            message: string;
            components: string[];
        };
        Error: {
            error: {
                code: string;
                message: string;
                request_id: string;
                retryable: boolean;
            };
        };
        AuthBootstrap: {
            /** @enum {string} */
            mode: "local-auth" | "local-admin";
            csrf_token: string;
        };
        AuthResult: {
            id: string;
            login: string;
            display_name: string;
            /** @constant */
            role: "user";
            /** Format: date-time */
            expires_at: string;
            csrf_token: string;
        };
        PasswordLogin: {
            login: string;
            password: string;
        };
        AcceptInvitation: {
            token: string;
            /** @description Minimum 12 Unicode characters, maximum 1024 UTF-8 bytes at runtime. */
            password: string;
        };
        RecoveryProof: {
            token: string;
            /** @description At least 12 Unicode characters and at most 1024 UTF-8 bytes. */
            new_password: string;
        };
        AdminChallenge: {
            challenge: string;
            /** Format: date-time */
            expires_at: string;
        };
        AdminTOTP: {
            challenge: string;
            code: string;
        };
        AdminAuthResult: {
            id: string;
            login: string;
            display_name: string;
            /** @constant */
            role: "admin";
            /** Format: date-time */
            expires_at: string;
            csrf_token: string;
        };
        DeviceQuota: {
            limit: number;
            used: number;
            remaining: number;
        };
        DeviceRequest: {
            request_id: string;
            name: string;
            /** @enum {string} */
            os: "ios" | "android" | "windows" | "macos" | "linux" | "other";
        };
        DeviceRevision: {
            expected_revision: number;
        };
        DeviceRename: {
            name: string;
            expected_revision: number;
        };
        AdminUser: {
            id: string;
            login: string;
            display_name: string;
            /** @enum {string} */
            state: "invited" | "active" | "disabled";
            device_limit: number;
            used_slots: number;
            /** @enum {string} */
            invitation: "available" | "expired" | "used" | "none";
            recovery_pending: boolean;
        };
        AdminProfile: {
            id: string;
            /** @enum {string} */
            protocol: "awg" | "reality";
            /** @enum {string} */
            state: "pending" | "ready" | "revoking" | "revoked" | "error";
            format: string;
            stored: boolean;
        };
        AdminDevice: {
            id: string;
            owner_id: string;
            owner_login: string;
            name: string;
            /** @enum {string} */
            os: "ios" | "android" | "windows" | "macos" | "linux" | "other";
            /** @enum {string} */
            state: "pending" | "active" | "partial" | "revoking" | "revoked" | "error";
            revision: number;
            generation: number;
            profiles: components["schemas"]["AdminProfile"][];
        };
        AdminAuditEvent: {
            id: string;
            action: string;
            /** @enum {string} */
            actor_kind: "trusted-cli" | "user" | "unknown";
            object_id: string;
            /** @enum {string} */
            outcome: "success" | "failed" | "unknown";
            /** Format: date-time */
            time: string;
        };
        AdminUserPage: {
            items: components["schemas"]["AdminUser"][];
            next_cursor: string;
        };
        AdminDevicePage: {
            items: components["schemas"]["AdminDevice"][];
            next_cursor: string;
        };
        AdminAuditEventPage: {
            items: components["schemas"]["AdminAuditEvent"][];
            next_cursor: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only demo response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    devices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only demo response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Device"][];
                    };
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    devices_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only demo response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only demo response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Health"][];
                    };
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    instructions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only demo response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Instruction"][];
                    };
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    admin_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only demo response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    downloadDemoProfile: {
        parameters: {
            query?: {
                format?: "txt";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NONFUNCTIONAL demo note; no VPN keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Not found/not ready/unsupported format */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process liveness; not VPN health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** @enum {string} */
                        mode: "demo";
                    };
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portal database responds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            /** @description Store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    authBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthBootstrap"];
                };
            };
            /** @description Standard error; no credential reflection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            429: {
                headers: {
                    /** @description Seconds until retry; fixed conservative 300 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    passwordLogin: {
        parameters: {
            query?: never;
            header: {
                Origin: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordLogin"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            /** @description Standard error; no credential reflection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            429: {
                headers: {
                    /** @description Seconds until retry; fixed conservative 300 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header: {
                Origin: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitation"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            /** @description Standard error; no credential reflection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            429: {
                headers: {
                    /** @description Seconds until retry; fixed conservative 300 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                Origin: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Success, no body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Standard error; no credential reflection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            429: {
                headers: {
                    /** @description Seconds until retry; fixed conservative 300 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    touchSession: {
        parameters: {
            query?: never;
            header: {
                Origin: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Success, no body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Standard error; no credential reflection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            429: {
                headers: {
                    /** @description Seconds until retry; fixed conservative 300 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    consumeRecovery: {
        parameters: {
            query?: never;
            header: {
                Origin: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryProof"];
            };
        };
        responses: {
            /** @description Password changed; no session created. Cookies cleared; bootstrap and ordinary login required. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Standard error; no credential reflection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            429: {
                headers: {
                    /** @description Seconds until retry; fixed conservative 300 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Standard error; no credential reflection */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    adminUsers: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            /** @description Sanitized API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    adminDevices: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
                state?: "all" | "pending" | "active" | "partial" | "revoking" | "revoked" | "error";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDevicePage"];
                };
            };
            /** @description Sanitized API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    adminAudit: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditEventPage"];
                };
            };
            /** @description Sanitized API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    offlineGuide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offline HTML attachment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
