package netguard

import (
	"encoding/json"
	"errors"
	"net/netip"
	"strings"
	"testing"
)

func dockerTopology(t *testing.T) (Inputs, Inventory, DockerScope) {
	t.Helper()
	i, v := topology("foreign")
	v.Interfaces = append(v.Interfaces, "amn0")
	v.Addresses = append(v.Addresses, Address{"amn0", netip.MustParsePrefix("172.29.172.1/24")})
	v.Routes = append(v.Routes, Route{"amn0", netip.MustParsePrefix("172.29.172.0/24")})
	scope, err := ForeignDockerScope(i, v)
	if err != nil {
		t.Fatal("synthetic scope rejected", err)
	}
	return i, v, scope
}

const dockerSave = `# Generated by iptables-save v1.8.4 (legacy)
*filter
:INPUT ACCEPT [12:256]
:FORWARD DROP [9:600]
:OUTPUT ACCEPT [8:400]
:DOCKER - [0:0]
:DOCKER-USER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o amn0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o amn0 -j DOCKER
-A FORWARD -i amn0 ! -o amn0 -j ACCEPT
-A FORWARD -i amn0 -o amn0 -j ACCEPT
-A DOCKER -d 172.29.172.2/32 ! -i amn0 -o amn0 -p udp -m udp --dport 30759 -j ACCEPT
-A DOCKER-USER -j RETURN
-A DOCKER-ISOLATION-STAGE-1 -i amn0 ! -o amn0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o amn0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
COMMIT
*nat
:PREROUTING ACCEPT [3:200]
:INPUT ACCEPT [2:100]
:OUTPUT ACCEPT [1:50]
:POSTROUTING ACCEPT [0:0]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 172.29.172.0/24 ! -o amn0 -j MASQUERADE
-A POSTROUTING -s 172.29.172.2/32 -d 172.29.172.2/32 -p udp -m udp --dport 30759 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A DOCKER -i amn0 -j RETURN
-A DOCKER ! -i amn0 -p udp -m udp --dport 30759 -j DNAT --to-destination 172.29.172.2:30759
COMMIT
# Completed
`

const emptyIPv6Save = `*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
`

func TestDockerScopeOnlyForeignDisjointObservedBridges(t *testing.T) {
	i, v, _ := dockerTopology(t)
	for _, mutate := range []func(*Inputs, *Inventory){
		func(i *Inputs, v *Inventory) { i.Role = "ru"; i.HostPublicIPv4 = i.RUIPv4 },
		func(i *Inputs, v *Inventory) { i.Transit = netip.MustParsePrefix("172.29.172.0/30") },
		func(i *Inputs, v *Inventory) {
			v.Addresses[len(v.Addresses)-1].Prefix = netip.MustParsePrefix("172.29.172.1/8")
		},
		func(i *Inputs, v *Inventory) {
			v.Addresses[len(v.Addresses)-1].Prefix = netip.MustParsePrefix("46.9.10.1/24")
		},
		func(i *Inputs, v *Inventory) { v.Addresses = append(v.Addresses, v.Addresses[len(v.Addresses)-1]) },
		func(i *Inputs, v *Inventory) {
			v.Addresses[len(v.Addresses)-1].Prefix = netip.MustParsePrefix("172.17.0.1/24")
		},
	} {
		copyV := v
		copyV.Addresses = append([]Address(nil), v.Addresses...)
		copyI := i
		mutate(&copyI, &copyV)
		if _, err := ForeignDockerScope(copyI, copyV); !errors.Is(err, ErrDockerScope) {
			t.Fatal("unsupported or overlapping scope accepted")
		}
	}
	if RequireScopedIPTables([]byte(dockerSave), "ip", DockerScope{}) == nil {
		t.Fatal("zero scope permits rewrite")
	}
}

func TestDockerLegacyClosedNATRecipesAndForwardingFence(t *testing.T) {
	_, _, scope := dockerTopology(t)
	if RequireScopedIPTables([]byte(dockerSave), "ip", scope) != nil || RequireScopedIPTables([]byte(emptyIPv6Save), "ip6", scope) != nil {
		t.Fatal("supported synthetic Docker listing rejected")
	}
	needed, err := LegacyForwardingNeedsGuard([]byte(dockerSave), scope)
	if err != nil || !needed || VerifyLegacyForwardingGuard([]byte(dockerSave), scope) == nil {
		t.Fatal("Docker default DROP falsely accepted as passing")
	}
	own := "-A FORWARD -i fvpn-host -j ACCEPT\n-A FORWARD -o fvpn-host -j ACCEPT\n"
	installed := strings.Replace(dockerSave, "-A FORWARD -j DOCKER-USER", own+"-A FORWARD -j DOCKER-USER", 1)
	if VerifyLegacyForwardingGuard([]byte(installed), scope) != nil {
		t.Fatal("exact owned head rejected")
	}
	before, e1 := LegacyPolicySHA256([]byte(dockerSave), "ip", scope, false)
	after, e2 := LegacyPolicySHA256([]byte(installed), "ip", scope, true)
	if e1 != nil || e2 != nil || before != after {
		t.Fatal("supplements changed original semantic baseline")
	}
	countersChanged := strings.ReplaceAll(installed, "[0:0]", "[9223372036854775808:18446744073709551615]")
	after, err = LegacyPolicySHA256([]byte(countersChanged), "ip", scope, true)
	if err != nil || after != before {
		t.Fatal("unsigned counter changes affect baseline")
	}
	modified := strings.Replace(installed, ":FORWARD DROP", ":FORWARD ACCEPT", 1)
	after, err = LegacyPolicySHA256([]byte(modified), "ip", scope, true)
	if err != nil || after == before {
		t.Fatal("Docker policy mutation hidden by own supplements")
	}
	for _, bad := range []string{
		strings.Replace(installed, "-i fvpn-host -j ACCEPT", "-i fvpn-host -m conntrack --ctstate NEW -j ACCEPT", 1),
		strings.Replace(installed, "-i fvpn-host -j ACCEPT", "-i fvpn-host -m conntrack -j ACCEPT", 1),
		strings.Replace(installed, "-i fvpn-host -j ACCEPT", "-i fvpn-host -m state -j ACCEPT", 1),
		strings.Replace(installed, "-i fvpn-host -j ACCEPT", "-i fvpn-host -m addrtype -j ACCEPT", 1),
		strings.Replace(installed, "-i fvpn-host -j ACCEPT", "-i fvpn-host -j DROP", 1),
		strings.Replace(installed, "-i fvpn-host -j ACCEPT", "-o fvpn-host -j ACCEPT", 1),
		strings.Replace(installed, "-A DOCKER-USER -j RETURN", "-A FORWARD -i fvpn-host -j ACCEPT\n-A DOCKER-USER -j RETURN", 1),
		strings.Replace(installed, own, "", 1),
	} {
		if VerifyLegacyForwardingGuard([]byte(bad), scope) == nil {
			t.Fatal("partial/reordered/duplicate/constrained owned acceptance accepted")
		}
	}
	if _, err := LegacyPolicySHA256([]byte(installed), "ip", scope, false); err == nil {
		t.Fatal("baseline accepts preexisting owned interface rules")
	}
}

func TestDockerLegacyRejectsRewriteOutsideProvenDisjointScope(t *testing.T) {
	_, _, scope := dockerTopology(t)
	for _, mutation := range [][2]string{
		{"--dst-type LOCAL", "--src-type LOCAL"},
		{"-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER", "-A PREROUTING -j DOCKER"},
		{"-s 172.29.172.0/24", "-s 0.0.0.0/0"},
		{"-s 172.29.172.0/24", "! -s 172.29.172.0/24"},
		{"-s 172.29.172.0/24", "-s 10.231.240.0/30"},
		{"! -o amn0 -j MASQUERADE", "! -o docker0 -j MASQUERADE"},
		{"--dport 30759 -j DNAT", "--dport 443 -j DNAT"},
		{"--dport 30759 -j DNAT", "--dport 30760 -j DNAT"},
		{"! -i amn0 -p udp", "-i amn0 -p udp"},
		{"172.29.172.2:30759", "10.231.240.2:30759"},
		{"172.29.172.2:30759", "172.29.172.1:30759"},
		{"172.29.172.2:30759", "172.29.172.2:443"},
		{"-j MASQUERADE", "-j MARK --set-mark 1"},
		{"-j MASQUERADE", "-j NFQUEUE"},
		{"-m udp --dport 30759 -j DNAT", "-m udp --dport 30759 -m unknown -j DNAT"},
		{"-j DNAT --to-destination", "-j REDIRECT --to-ports"},
		{"-p udp -m udp --dport 30759 -j DNAT", "-p tcp -m tcp --dport 30759 -j DNAT"},
		{"-A DOCKER ! -i amn0", "-A POSTROUTING ! -i amn0"},
	} {
		bad := strings.Replace(dockerSave, mutation[0], mutation[1], 1)
		if bad == dockerSave {
			t.Fatal("test mutation did not match")
		}
		if RequireScopedIPTables([]byte(bad), "ip", scope) == nil {
			t.Fatal("unsupported Docker rule accepted", mutation[0])
		}
	}
	for _, injection := range []string{
		"-A FORWARD -j CT\n", "-A FORWARD -j MARK\n", "-A FORWARD -j QUEUE\n", "-A FORWARD -j TPROXY\n", "-A FORWARD -j TRACE\n",
	} {
		bad := strings.Replace(dockerSave, "-A FORWARD -j DOCKER-USER", injection+"-A FORWARD -j DOCKER-USER", 1)
		if RequireScopedIPTables([]byte(bad), "ip", scope) == nil {
			t.Fatal("unknown/assignment legacy target accepted")
		}
	}
	// Renaming a user chain to a reserved extension cannot hide target effects.
	bad := strings.ReplaceAll(dockerSave, "DOCKER-USER", "MARK")
	if RequireScopedIPTables([]byte(bad), "ip", scope) == nil {
		t.Fatal("reserved extension shadow chain accepted")
	}
	if RequireScopedIPTables([]byte(dockerSave), "ip6", scope) == nil {
		t.Fatal("IPv6 NAT accepted through IPv4 bridge subset")
	}
}

func TestDockerLegacyRejectsMalformedOrIncompleteReadback(t *testing.T) {
	_, _, scope := dockerTopology(t)
	for _, bad := range []string{
		strings.Replace(dockerSave, "COMMIT", "", 1),
		strings.Replace(dockerSave, "*filter", "*unknown", 1),
		strings.Replace(dockerSave, ":FORWARD DROP [9:600]", ":FORWARD DROP [18446744073709551616:0]", 1),
		strings.Replace(dockerSave, ":FORWARD DROP [9:600]", ":FORWARD DROP [-1:0]", 1),
		strings.Replace(dockerSave, ":DOCKER - [0:0]", ":DOCKER - [0:0]\n:DOCKER - [0:0]", 1),
		strings.Replace(dockerSave, "-A FORWARD -j DOCKER-USER", "-I FORWARD -j DOCKER-USER", 1),
		strings.Replace(dockerSave, "-A FORWARD -j DOCKER-USER", "-A FORWARD -j DOCKER-USER -j ACCEPT", 1),
		strings.Replace(dockerSave, "-A FORWARD -j DOCKER-USER", "-A FORWARD -j $(id)", 1),
		dockerSave + "COMMIT\n", dockerSave + "\x00", strings.Repeat("#x\n", 8193), strings.Repeat("x", 1024*1024+1),
	} {
		if RequireScopedIPTables([]byte(bad), "ip", scope) == nil {
			t.Fatal("malformed/incomplete legacy listing accepted")
		}
	}
}

func dockerNft(t *testing.T, own bool) []byte {
	t.Helper()
	objects := []any{
		map[string]any{"metainfo": map[string]any{"version": "0.9.3", "release_name": "fixture", "json_schema_version": 1}},
		map[string]any{"table": map[string]any{"family": "ip", "name": "filter", "handle": 1}},
		map[string]any{"chain": map[string]any{"family": "ip", "table": "filter", "name": "FORWARD", "type": "filter", "hook": "forward", "prio": 0, "policy": "drop", "handle": 2}},
	}
	if own {
		for _, key := range []string{"iifname", "oifname"} {
			objects = append(objects, map[string]any{"rule": map[string]any{"family": "ip", "table": "filter", "chain": "FORWARD", "expr": ownedForwardNFT(key)}})
		}
	}
	objects = append(objects,
		map[string]any{"rule": map[string]any{"family": "ip", "table": "filter", "chain": "FORWARD", "expr": []any{map[string]any{"counter": map[string]any{"packets": 10, "bytes": 400}}, map[string]any{"drop": nil}}}},
		map[string]any{"table": map[string]any{"family": "ip", "name": "nat"}},
	)
	for _, q := range []struct {
		name, hook string
		priority   int
	}{{"PREROUTING", "prerouting", -100}, {"INPUT", "input", 100}, {"OUTPUT", "output", -100}, {"POSTROUTING", "postrouting", 100}} {
		objects = append(objects, map[string]any{"chain": map[string]any{"family": "ip", "table": "nat", "name": q.name, "type": "nat", "hook": q.hook, "prio": q.priority, "policy": "accept"}})
	}
	objects = append(objects, map[string]any{"chain": map[string]any{"family": "ip", "table": "nat", "name": "DOCKER"}})
	match := func(left any, op string, right any) any {
		return map[string]any{"match": map[string]any{"op": op, "left": left, "right": right}}
	}
	payload := func(protocol, field string) any {
		return map[string]any{"payload": map[string]any{"protocol": protocol, "field": field}}
	}
	meta := func(key string) any { return map[string]any{"meta": map[string]any{"key": key}} }
	rule := func(chain string, expr ...any) {
		objects = append(objects, map[string]any{"rule": map[string]any{"family": "ip", "table": "nat", "chain": chain, "expr": expr}})
	}
	for _, chain := range []string{"PREROUTING", "OUTPUT"} {
		rule(chain, match(map[string]any{"fib": map[string]any{"result": "type", "flags": []any{"daddr"}}}, "==", "local"), map[string]any{"counter": map[string]any{"packets": 0, "bytes": 0}}, map[string]any{"jump": map[string]any{"target": "DOCKER"}})
	}
	rule("POSTROUTING", match(payload("ip", "saddr"), "==", map[string]any{"prefix": map[string]any{"addr": "172.29.172.0", "len": 24}}), match(meta("oifname"), "!=", "amn0"), map[string]any{"masquerade": nil})
	rule("DOCKER", match(meta("iifname"), "==", "amn0"), map[string]any{"return": nil})
	rule("DOCKER", match(meta("iifname"), "!=", "amn0"), match(meta("l4proto"), "==", "udp"), match(payload("udp", "dport"), "==", 30759), map[string]any{"dnat": map[string]any{"addr": "172.29.172.2", "port": 30759}})
	b, err := json.Marshal(map[string]any{"nftables": objects})
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func TestDockerNftClosedSubsetKeepsStrictGateAndBaseline(t *testing.T) {
	_, _, scope := dockerTopology(t)
	before, installed := dockerNft(t, false), dockerNft(t, true)
	if RequireNoUnownedPacketRewrite(before) == nil || RequireScopedHostRewrite(before, scope) != nil {
		t.Fatal("scoped exception weakened original strict gate or rejected supported recipe")
	}
	needed, err := NFTForwardingNeedsGuard(before, scope)
	if err != nil || !needed || VerifyNFTForwardingGuard(before, scope) == nil || VerifyNFTForwardingGuard(installed, scope) != nil {
		t.Fatal("shared DROP policy reachability was not separately fenced")
	}
	if _, err := NFTPolicySHA256(installed, scope, false); err == nil {
		t.Fatal("nft baseline accepts preexisting owned interface rules")
	}
	a, e1 := NFTPolicySHA256(before, scope, false)
	b, e2 := NFTPolicySHA256(installed, scope, true)
	if e1 != nil || e2 != nil || a != b {
		t.Fatal("owned supplements changed nft baseline", e1, e2)
	}
	changed := strings.Replace(string(installed), `"packets":10`, `"packets":22`, 1)
	b, err = NFTPolicySHA256([]byte(changed), scope, true)
	if err != nil || a != b {
		t.Fatal("counter change affected semantic baseline")
	}
	changed = strings.Replace(string(installed), `"policy":"drop"`, `"policy":"accept"`, 1)
	b, err = NFTPolicySHA256([]byte(changed), scope, true)
	if err != nil || a == b {
		t.Fatal("unrelated policy mutation hidden")
	}
	for _, mutation := range [][2]string{
		{`"flags":["daddr"]`, `"flags":["saddr"]`},
		{`"right":30759`, `"right":443`},
		{`"addr":"172.29.172.2"`, `"addr":"10.231.240.2"`},
		{`"addr":"172.29.172.0","len":24`, `"addr":"0.0.0.0","len":0`},
		{`"masquerade":null`, `"mangle":{"key":{"meta":{"key":"mark"}},"value":1}`},
		{`"masquerade":null`, `"queue":{"num":0}`},
		{`"masquerade":null`, `"flow":{"op":"add","flowtable":"f"}`},
		{`"masquerade":null`, `"xt":{"name":"MASQUERADE","rev":0,"type":"target"}`},
		{`"prio":-100`, `"prio":-200`},
	} {
		bad := strings.Replace(string(before), mutation[0], mutation[1], 1)
		if bad == string(before) || RequireScopedHostRewrite([]byte(bad), scope) == nil {
			t.Fatal("unsupported nft rewrite/priority accepted", mutation[0])
		}
	}
	for _, bad := range [][]byte{nil, []byte(`{"nftables":[],"nftables":[]}`), append(before, []byte(`{}`)...)} {
		if RequireScopedHostRewrite(bad, scope) == nil {
			t.Fatal("malformed nft listing accepted")
		}
	}
}

func TestDockerForwardInsertionScopesPreserveUnownedTraffic(t *testing.T) {
	for _, backend := range []string{"legacy", "nft"} {
		steps, err := DockerForwardInsertions(backend)
		if err != nil || len(steps) != 2 {
			t.Fatal("closed supplement missing")
		}
		for _, step := range steps {
			if step.Scope != "host" || !strings.Contains(strings.Join(step.Args, " "), HostVeth) || len(step.Stdin) != 0 {
				t.Fatal("shared filter mutation exceeds owned interface scope")
			}
			if backend == "legacy" && (!strings.Contains(strings.Join(step.Args, " "), "-M "+LegacyDisableModuleAutoload) || !strings.Contains(strings.Join(step.Args, " "), "-w 2")) {
				t.Fatal("legacy fixed module deny and bounded lock missing")
			}
			for _, token := range step.Args {
				if token == "flush" || token == "-F" || token == "-P" || token == "policy" || token == "DROP" || token == "ESTABLISHED" {
					t.Fatal("broad Docker mutation or blanket established acceptance")
				}
			}
		}
	}
	if _, err := DockerForwardInsertions("auto"); err == nil {
		t.Fatal("backend autopick accepted")
	}
}

func TestDockerNftNamedCounterIdentityAndHandlesRemainFenced(t *testing.T) {
	_, _, scope := dockerTopology(t)
	data := string(dockerNft(t, false))
	anon := `"counter":{"bytes":400,"packets":10}`
	named := strings.Replace(data, anon, `"counter":"first_counter"`, 1)
	if named == data {
		t.Fatal("named counter test did not replace anonymous expression")
	}
	a, err := NFTPolicySHA256([]byte(named), scope, false)
	if err != nil {
		t.Fatal("read-only named counter rejected")
	}
	b, err := NFTPolicySHA256([]byte(strings.Replace(named, `"first_counter"`, `"second_counter"`, 1)), scope, false)
	if err != nil || a == b {
		t.Fatal("named counter identity erased from baseline")
	}
	b, err = NFTPolicySHA256([]byte(strings.Replace(named, `"handle":1`, `"handle":1234`, 1)), scope, false)
	if err != nil || a != b {
		t.Fatal("dump handle becomes semantic baseline")
	}
	for _, handle := range []string{"0", "-1", "18446744073709551616", `"arbitrary"`} {
		bad := strings.Replace(named, `"handle":1`, `"handle":`+handle, 1)
		if _, err := NFTPolicySHA256([]byte(bad), scope, false); err == nil {
			t.Fatal("malformed handle accepted")
		}
	}
}

func TestDockerNftOwnedForwardHeadIsExactAndNeverHiddenByBaseline(t *testing.T) {
	_, _, scope := dockerTopology(t)
	data := string(dockerNft(t, true))
	for _, mutation := range [][2]string{
		{`"key":"iifname"`, `"key":"oifname"`},
		{`"right":"fvpn-host"`, `"right":"amn0"`},
		{`"op":"=="`, `"op":"!="`},
		{`"accept":null`, `"drop":null`},
		{`"accept":null`, `"counter":{"packets":0,"bytes":0}`},
		{`"prio":0`, `"prio":300`},
	} {
		bad := strings.Replace(data, mutation[0], mutation[1], 1)
		if VerifyNFTForwardingGuard([]byte(bad), scope) == nil {
			t.Fatal("mutated owned head accepted", mutation[0])
		}
		if _, err := NFTPolicySHA256([]byte(bad), scope, true); err == nil {
			t.Fatal("baseline erased malformed owned head")
		}
	}
	var root map[string]any
	if json.Unmarshal([]byte(data), &root) != nil {
		t.Fatal("fixture JSON invalid")
	}
	objects := root["nftables"].([]any)
	objects = append(objects, map[string]any{"rule": map[string]any{"family": "ip", "table": "filter", "chain": "FORWARD", "expr": ownedForwardNFT("iifname")}})
	root["nftables"] = objects
	duplicate, err := json.Marshal(root)
	if err != nil || VerifyNFTForwardingGuard(duplicate, scope) == nil {
		t.Fatal("duplicate owned head accepted")
	}
}
