package clientconfig

import (
	"bytes"
	"crypto/ecdh"
	"encoding/base64"
	"encoding/hex"
	"familyvpn.local/platform/internal/profilevault"
	"net"
	"net/netip"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// AWG31Conf is a deliberately bounded client export, never an awg-quick script.
const AWG31Conf = "awg-3.1-conf"

func awgNumber(s string, bits int) (uint64, bool) {
	if s == "" {
		return 0, false
	}
	for _, c := range s {
		if c < '0' || c > '9' {
			return 0, false
		}
	}
	n, e := strconv.ParseUint(s, 10, bits)
	return n, e == nil
}

func awgRange(s string, bits int) (uint64, uint64, bool) {
	a, b, pair := strings.Cut(s, "-")
	lo, ok := awgNumber(a, bits)
	if !ok {
		return 0, 0, false
	}
	if !pair {
		return lo, lo, true
	}
	hi, ok := awgNumber(b, bits)
	return lo, hi, ok && lo <= hi
}

func awgKey(s string) ([]byte, bool) {
	if len(s) != 44 {
		return nil, false
	}
	b, e := base64.StdEncoding.Strict().DecodeString(s)
	if e != nil || len(b) != 32 || bytes.Equal(b, make([]byte, 32)) {
		clear(b)
		return nil, false
	}
	return b, true
}

// ValidAWGEndpoint validates the existing lexical subset without DNS/network I/O.
func ValidAWGEndpoint(s string) bool { return awgEndpoint(s) }

func awgEndpoint(s string) bool {
	host, port, e := net.SplitHostPort(s)
	n, ok := awgNumber(port, 16)
	if e != nil || !ok || n == 0 {
		return false
	}
	if ip, e := netip.ParseAddr(host); e == nil {
		return ip.Zone() == "" && !ip.IsUnspecified() && !ip.IsMulticast() && (!strings.HasPrefix(s, "[") || ip.Is6())
	}
	return !strings.HasPrefix(s, "[") && hostname(host)
}

func awgAddresses(s string, dns bool) bool {
	parts := strings.Split(s, ",")
	if len(parts) == 0 || len(parts) > 8 {
		return false
	}
	seen := map[netip.Addr]bool{}
	for _, part := range parts {
		var ip netip.Addr
		if dns {
			parsed, e := netip.ParseAddr(strings.TrimSpace(part))
			if e != nil {
				return false
			}
			ip = parsed
		} else {
			prefix, e := netip.ParsePrefix(strings.TrimSpace(part))
			if e != nil || prefix.Bits() == 0 {
				return false
			}
			ip = prefix.Addr()
		}
		if seen[ip] || ip.Zone() != "" || ip.IsUnspecified() || ip.IsMulticast() || ip.Is4In6() {
			return false
		}
		seen[ip] = true
	}
	return true
}

// The M1 importer accepts IPv4 full tunnel, optionally also IPv6 full tunnel.
// This is not evidence of DNS/IPv6 leak prevention on a real device.
func awgFullTunnel(s string) bool {
	seen := map[string]bool{}
	for _, part := range strings.Split(s, ",") {
		p, e := netip.ParsePrefix(strings.TrimSpace(part))
		if e != nil || p.Bits() != 0 || !p.Addr().IsUnspecified() || p.Addr().Is4In6() || seen[p.String()] {
			return false
		}
		seen[p.String()] = true
	}
	return seen["0.0.0.0/0"] && len(seen) <= 2
}

// Validate documented CPS tags without interpreting them or generating packets.
// Bounded subset: <=128 tags and <=4096 generated bytes per I packet.
func awgCPS(s string) bool {
	total, count, timestamps := 0, 0, 0
	for s != "" {
		if !strings.HasPrefix(s, "<") {
			return false
		}
		i := strings.IndexByte(s, '>')
		if i < 0 {
			return false
		}
		fields := strings.Fields(s[1:i])
		s = s[i+1:]
		count++
		if len(fields) == 1 && fields[0] == "t" {
			timestamps++
			total += 4
		} else if len(fields) == 2 {
			switch fields[0] {
			case "b":
				value := strings.TrimPrefix(fields[1], "0x")
				if value == "" || len(value)%2 != 0 {
					return false
				}
				decoded, e := hex.DecodeString(value)
				clear(decoded)
				if e != nil {
					return false
				}
				total += len(value) / 2
			case "r", "rc", "rd":
				n, ok := awgNumber(fields[1], 16)
				if !ok || n == 0 || n > 1000 {
					return false
				}
				total += int(n)
			default:
				return false
			}
		} else {
			return false
		}
		if timestamps > 1 || total > 4096 || count > 128 {
			return false
		}
	}
	return count > 0
}

func validateAWG31(data []byte) (Validated, error) {
	invalid := func() (Validated, error) { return Validated{}, ErrInvalid }
	if len(data) == 0 || len(data) > profilevault.MaxSize || !utf8.Valid(data) {
		return invalid()
	}
	for _, c := range string(data) {
		if (unicode.IsControl(c) && c != '\n' && c != '\r' && c != '\t') || unicode.Is(unicode.Cf, c) {
			return invalid()
		}
	}
	iface, peer := map[string]string{}, map[string]string{}
	section := ""
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSuffix(raw, "\r")
		if strings.ContainsRune(line, '\r') {
			return invalid()
		}
		line, _, _ = strings.Cut(line, "#")
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if strings.EqualFold(line, "[Interface]") && section == "" {
			section = "interface"
			continue
		}
		if strings.EqualFold(line, "[Peer]") && section == "interface" {
			section = "peer"
			continue
		}
		if section == "" || strings.HasPrefix(line, "[") {
			return invalid()
		}
		key, value, ok := strings.Cut(line, "=")
		key, value = strings.ToLower(strings.TrimSpace(key)), strings.TrimSpace(value)
		if !ok || value == "" {
			return invalid()
		}
		fields := iface
		if section == "peer" {
			fields = peer
		}
		if _, duplicate := fields[key]; duplicate {
			return invalid()
		}
		fields[key] = value
	}
	if section != "peer" {
		return invalid()
	}
	for key, value := range iface {
		ok := false
		switch key {
		case "privatekey", "headerprotectionkey":
			b, valid := awgKey(value)
			clear(b)
			ok = valid
		case "address":
			ok = awgAddresses(value, false)
		case "dns":
			ok = awgAddresses(value, true)
		case "jc", "jmin", "jmax", "s1", "s2", "s3", "s4", "listenport":
			_, ok = awgNumber(value, 16)
		case "mtu":
			n, valid := awgNumber(value, 16)
			ok = valid && n >= 576
		case "h1", "h2", "h3", "h4":
			_, _, ok = awgRange(value, 32)
		case "contentpaddingaddition", "rekeyaftertime", "rekeytimeout", "rejectaftertime", "keepalivetimeout", "maxhandshakeattempts":
			_, _, ok = awgRange(value, 16)
		case "randomtrailers", "disablecookies":
			ok = value == "on" || value == "off"
		case "i1", "i2", "i3", "i4", "i5":
			ok = awgCPS(value)
		}
		if !ok {
			return invalid()
		}
	}
	for _, key := range []string{"privatekey", "address", "dns", "jc", "jmin", "jmax", "s1", "s2", "s3", "s4", "h1", "h2", "h3", "h4", "headerprotectionkey"} {
		if iface[key] == "" {
			return invalid()
		}
	}
	min, _ := awgNumber(iface["jmin"], 16)
	max, _ := awgNumber(iface["jmax"], 16)
	if min > max {
		return invalid()
	}
	var headers [4][2]uint64
	var sizes [4]uint64
	for i := range headers {
		sizes[i], _ = awgNumber(iface["s"+strconv.Itoa(i+1)], 16)
		if sizes[i] < 12 || (iface["randomtrailers"] == "on" && sizes[i] != sizes[0]) {
			return invalid()
		}
		headers[i][0], headers[i][1], _ = awgRange(iface["h"+strconv.Itoa(i+1)], 32)
		for j := 0; j < i; j++ {
			if headers[i][0] <= headers[j][1] && headers[j][0] <= headers[i][1] {
				return invalid()
			}
		}
	}
	for key, value := range peer {
		ok := false
		switch key {
		case "publickey", "presharedkey":
			b, valid := awgKey(value)
			clear(b)
			ok = valid
		case "endpoint":
			ok = awgEndpoint(value)
		case "allowedips":
			ok = awgFullTunnel(value)
		case "persistentkeepalive":
			_, _, ok = awgRange(value, 16)
		case "advancedsecurity":
			ok = value == "on" // Don't import an explicitly disabled AWG peer.
		}
		if !ok {
			return invalid()
		}
	}
	for _, key := range []string{"publickey", "endpoint", "allowedips"} {
		if peer[key] == "" {
			return invalid()
		}
	}
	private, _ := awgKey(iface["privatekey"])
	defer clear(private)
	key, e := ecdh.X25519().NewPrivateKey(private)
	if e != nil {
		return invalid()
	}
	// Public identity catches even different encodings of the same clamped private key.
	result := Validated{Protocol: "awg", Format: AWG31Conf}
	copy(result.credential[:], key.PublicKey().Bytes())
	return result, nil
}
